load("@rules_python//python:defs.bzl", "py_test")

[
    py_test(
        name = "target_%d" % index,
        srcs = [
            "test_demo.py",
            "test_runner.py",
        ],
        main = "test_runner.py",
        args = [str(index)],
        deps = ["@demo_pypi//pytest"],
        legacy_create_init = 0,
    )
    for index in range(1000)
]
